name = "backend"
main = "build/worker/shim.mjs"
compatibility_date = "2025-07-24"

[build]
command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source ~/.cargo/env && cargo install -q worker-build && worker-build --release"
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "2ca2406e-ce38-498c-a21c-b5efdb51d937"

[observability.logs]
enabled = true

